# config file version
apiVersion: 1

# List of contact points to import or update
contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: controller-webhook
    receivers:
      # <string, required> unique identifier for the receiver
      - uid: controller-webhook
        # <string, required> type of the receiver
        type: webhook
        settings:
          # <string, required>
          url: http://host.docker.internal:1111/grafana_alert
          # <string> options: POST, PUT
          httpMethod: POST