{
 "title": "Indexing Performance Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Individual subgraph sync rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "deriv(deployment_head[10m]) * 60",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "All subgraphs sync rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(deriv(deployment_head[10m]) * 60)",
     "legendFormat": "Total Sync Rate"
    }
   ]
  },
  {
   "title": "Blocks behind over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "abs(deployment_head{instance=\"index-node-0:8040\"} - on (network) group_left ethereum_chain_head_number{instance=\"index-node-0:8040\"})",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "abs(deployment_head{instance=\"index-node-1:8040\"} - on (network) group_left ethereum_chain_head_number{instance=\"index-node-1:8040\"})",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "abs(deployment_head{instance=\"query-node-gnosis:8040\"} - on (network) group_left ethereum_chain_head_number{instance=\"query-node-gnosis:8040\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Eth RPC Request Duration per Subgraph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(deployment_eth_rpc_request_duration[15m])",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Eth RPC Errors per minute (all subgraphs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(eth_rpc_errors[1m]))"
    }
   ]
  }
 ]
}