[store]
[store.primary]
connection = "postgresql://graph_user:graph_db_password@postgres:5432/graph_db?host=/var/run/postgresql"
pool_size = 10


[chains]
ingestor = "index_node_0"

[chains.mainnet]
shard = "primary"
provider = [ { label = "mainnet", url = "https://upnodedev:w3tbUpvTRoSCT8wd@eth-archive.upnodedev.xyz", features = ["archive", "traces"] } ]

[chains.gnosis]
shard = "primary"
provider = [ { label = "gnosis", url = "http://gnosis-archive.upnodedev.xyz", features = ["archive", "traces"] } ]

[deployment]
[[deployment.rule]]
indexers = [ "index_node_0" ]


[general]
query = "query_node_0"
